### ISSUE TITLE
more tools missing

### ISSUE THREAD

**Issue by alexmyczko** [psykon/awesome-demoscene#3]
[hivelytracker](https://github.com/pete-gordon/hivelytracker) - Music tracker for AHX and HVL formats
[pt2-clone](https://16-bits.org/pt.php) - Music tracker clone of ProTracker 2 for modern computers
[ft2-clone](https://16-bits.org/ft2.php) - Fasttracker II clone
[grafx2](http://pulkomandy.tk/projects/GrafX2) - ultimate 256-color bitmap paint program
[komposter](http://komposter.haxor.fi/) - lightweight music composing system
[bambootracker](https://github.com/rerrahkr/BambooTracker) -YM2608 (OPNA, sound chip of Yamaha) music tracker
[klystrack](https://github.com/kometbomb/klystrack) - Chiptune tracker
[goattracker](https://cadaver.github.io/tools.html) - C64 music editor
[cheesecutter](http://theyamo.kapsi.fi/ccutter) - SID music editor
[furnace](https://github.com/tildearrow/furnace) - multi-system chiptune tracker compatible with DefleMask modules
[schism tracker](http://schismtracker.org/) - ImpulseTracker clone aiming at providing the same look&feel

... now it's almost a pull request...

**Comment by psykon** [comment]
Thanks! I added them all in #[7332bbb](https://github.com/psykon/awesome-demoscene/commit/7332bbb76daaa36fa0fb14db72ae7efe13441af4).
